Pin 1315 authorization-process GET /clients
pagopa/interop-be-authorization-process pull request #203
Opened 2023-03-09 16:24 UTC by nttdata-rtorsoli

2023-03-15 09:23 UTC, galales requested changes

2023-03-15 09:23 UTC, galales commented on src/main/resources/interface-specification.yml
> -        - name: consumerId
we should keep the existing filters for services that use them

2023-03-15 09:23 UTC, galales commented on src/main/resources/interface-specification.yml
> -        - name: purposeId
same, let's keep this filter

2023-03-15 09:23 UTC, galales commented on src/main/resources/interface-specification.yml
> -        - name: kind
same, let's keep this filter

2023-03-15 09:23 UTC, galales commented on src/main/resources/interface-specification.yml
> +        consumer:
Note: the returned model should be exactly the one in the read model, unless we need to hide informations
```suggestion
        consumerId:
```

2023-03-15 09:23 UTC, galales commented on src/main/resources/interface-specification.yml
> +        relationships:
```suggestion
        relationshipsIds:
```

2023-03-15 09:23 UTC, galales commented on src/main/scala/it/pagopa/interop/authorizationprocess/api/impl/ClientApiHandlers.scala
ℹ️ remember to delete the old `listClientsResponse`

2023-03-15 09:23 UTC, galales commented on src/test/resources/authz.json
ℹ️ remember to remove the configuration for `listClients`

2023-03-15 09:23 UTC, galales commented on src/main/scala/it/pagopa/interop/authorizationprocess/api/impl/ClientApiServiceImpl.scala
> +    val result: Future[Clients] = for {
⚠️ the [permissions check](https://github.com/pagopa/interop-be-authorization-process/pull/203/files?diff=split&w=1#diff-209aa1b53c41d816589a5ccda66c676d1eb0c523ee48138033a3e7e3d4e27b85L159) has been removed. 
It is required to 
- allow admin users to see all their clients, even if they are not included in the relationships
- if user is not an admin, return only clients that includes the relationship id of the user-entity

2023-03-16 17:30 UTC, galales commented on src/main/scala/it/pagopa/interop/authorizationprocess/common/readmodel/ReadModelQueries.scala
> +    val kindFilter            = kind.map(Filters.regex("data.kind", _, "i"))
No need for regex here
```suggestion
    val kindFilter            = kind.map(k => Filters.eq("data.kind", k.toString))
```

2023-03-16 17:30 UTC, galales commented on src/main/scala/it/pagopa/interop/authorizationprocess/common/readmodel/ReadModelQueries.scala
> +    kind: Option[String]
```suggestion
    kind: Option[PersistentClientKind]
```

2023-03-16 17:30 UTC, galales commented on src/main/scala/it/pagopa/interop/authorizationprocess/common/readmodel/ReadModelQueries.scala
> +    val purposeFilter         = purposeId.map(Filters.in("data.purposes", _))
are we sure this is working?
I would expect something like
```suggestion
    val purposeFilter         = purposeId.map(Filters.eq("data.purposes.purpose.purposeId", _))
```

2023-03-16 17:30 UTC, galales commented on src/main/scala/it/pagopa/interop/authorizationprocess/common/readmodel/ReadModelQueries.scala
> +    kind: Option[String],
let's keep them typed
```suggestion
    relationshipIds: List[UUID],
    consumerId: UUID,
    purposeId: Option[UUID],
    kind: Option[PersistentClientKind],
```

2023-03-16 17:30 UTC, galales commented on src/main/scala/it/pagopa/interop/authorizationprocess/api/impl/ClientApiServiceImpl.scala
> +    } yield List(relationshipId)
```suggestion
    def getRelationships(userId: UUID, consumerId: UUID): Future[List[UUID]] = 
      securityOperatorRelationship(consumerId, userId, Seq(SECURITY_ROLE)).map(_.id)
```

2023-03-16 17:30 UTC, galales commented on src/main/scala/it/pagopa/interop/authorizationprocess/api/impl/ClientApiServiceImpl.scala
> +        else Future.successful(parseArrayParameters(relationshipIds))
```suggestion
        else parseArrayParameters(relationshipIds).traverse(_.toUuid).toFuture
```

2023-03-17 11:18 UTC, TonioGela approved these changes

2023-03-17 11:18 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/authorizationprocess/api/impl/ClientApiServiceImpl.scala
> +      purposeUUid   <- purposeId.map(_.toFutureUUID).sequence
```suggestion
      purposeUUid   <- purposeId.traverse(_.toFutureUUID)
```

2023-03-17 13:09 UTC, galales approved these changes

2023-03-17 13:17 UTC, merged