[PIN-3447] Integrated support role to authorization process
pagopa/interop-be-authorization-process pull request #216
Opened 2023-05-29 11:09 UTC by rGregnanin

2023-05-30 07:56 UTC, galales requested changes
missing `getClientOperatorRelationshipById`

2023-05-30 12:48 UTC, galales commented
> missing `getClientOperatorRelationshipById`

nvm, it has recently been removed

2023-05-30 12:48 UTC, galales approved these changes

2023-05-31 08:40 UTC, beetlecrunch commented
LGTM, I noticed that the authorization test for the `getClientsWithKeys` function is completely missing.
Could you add it (src/test/resources/authz.json)?
Thank you!

2023-05-31 09:24 UTC, TonioGela commented on src/test/resources/authz.json
> +      "route": "getClientsWithKeys",
Please pay attention, as that's not enough, you should add the test that uses this value, exactly like in other cases too.

2023-05-31 09:54 UTC, rGregnanin commented on src/test/resources/authz.json
> +      "route": "getClientsWithKeys",
Like the other PR i apologize for the misunderstanding, next time I pay more attention

2023-05-31 13:37 UTC, TonioGela approved these changes

2023-05-31 13:41 UTC, merged