PIN-4999 BKE - Auth process - SECURITY role is not allowed to delete keys if it is not longer a client member
pagopa/interop-be-authorization-process pull request #245
Opened 2024-06-20 08:53 UTC by nttdata-rtorsoli

2024-06-24 10:46 UTC, galales requested changes

2024-06-24 10:46 UTC, galales commented on src/main/scala/it/pagopa/interop/authorizationprocess/api/impl/ClientApiServiceImpl.scala
> +    } yield ()
note: even admins cannot perform operations on a client where they are not members, we can skip role check

```suggestion
    def assertUserIsMemberOfClient(client: PersistentClient): Future[Unit] = for {
      requesterUserId <- getUidFutureUUID(contexts)
      _               <-
        if (!client.users.contains(requesterUserId))
          Future.failed(KeyOperationNotAllowedOnClient(client.id))
        else Future.unit
    } yield ()
```

2024-06-24 10:46 UTC, galales commented on src/main/scala/it/pagopa/interop/authorizationprocess/api/impl/ClientApiServiceImpl.scala
>        _          <- assertIsClientConsumer(client).toFuture
let's check first that the requester is the consumer
```suggestion
      _          <- assertIsClientConsumer(client).toFuture
      _          <- checkRole(client)
```

2024-06-24 10:46 UTC, galales commented on src/main/scala/it/pagopa/interop/authorizationprocess/error/AuthorizationProcessErrors.scala
> +        s"Role is not allowed to perform operation on the key for the client ${clientId.toString}"
```suggestion
  final case class UserIsNotMemberOfClient(clientId: UUID, userId: UUID)
      extends ComponentError(
        "0025",
        s"User $userId is not a member of client ${clientId.toString}"
```

2024-06-25 09:17 UTC, galales commented on src/main/scala/it/pagopa/interop/authorizationprocess/api/impl/ClientApiServiceImpl.scala
>        _          <- assertIsClientConsumer(client).toFuture
may you move consumer check before member check?
```suggestion
      _          <- assertIsClientConsumer(client).toFuture
      _          <- assertUserIsMemberOfClient(client)
```

2024-07-01 08:39 UTC, galales approved these changes

2024-07-10 08:51 UTC, beetlecrunch commented
This is fixed in the new module.

2024-07-10 08:51 UTC, closed without merging